services:
  - type: web
    name: bot-shield
    env: node
    plan: starter
    buildCommand: npm ci && npx prisma generate && npm run build
    startCommand: npm run setup && npm run start
    autoDeploy: true
