# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d4fd10812566b17d9d99ed95e0978ada"
name = "BotShield"
application_url = "https://botshield-backend.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = false
include_config_on_deploy = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request" ]
  uri = "/webhooks/customers/data_request"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/redact" ]
  uri = "/webhooks/customers/redact"

  [[webhooks.subscriptions]]
  compliance_topics = [ "shop/redact" ]
  uri = "/webhooks/shop/redact"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_app_proxy"
optional_scopes = [ "read_orders" ]

[app_proxy]
url = "/proxy/botshield"
subpath = "botshield"
prefix = "apps"

[auth]
redirect_urls = [ "https://botshield-backend.onrender.com/auth/callback" ]
