import { PublicLegalShell, PublicSupportEmailLink } from "../components/public/PublicLegalShell";
import { publicInfo } from "../config/public-info";

export const meta = () => [{ title: `Data Use | ${publicInfo.appName}` }];

export default function DataUsePage() {
  return (
    <PublicLegalShell title="Data Use">
      <p>
        This page explains how {publicInfo.appName} uses information to operate
        its storefront security, analytics, alerts, enforcement, and optional
        Fraud Orders review features. It summarizes the categories of data
        involved based on the app&apos;s current implementation.
      </p>
      <h2>Store And App Information</h2>
      <p>BotShield may process:</p>
      <ul>
        <li>Shopify store domain and shop identifiers needed to associate activity with the correct merchant installation</li>
        <li>App installation, authentication, and session records required to operate the embedded Shopify admin app</li>
        <li>Merchant configuration such as protection settings, alert routing, blocklists, whitelists, analyst notes, and trusted tags</li>
        <li>Billing and subscription status metadata needed to show plan state inside the app</li>
      </ul>
      <h2>Storefront Security Telemetry</h2>
      <p>
        When the BotShield theme app embed is enabled, compatible storefront
        browsers may send request context that BotShield uses for security
        analysis. Depending on the event, BotShield may process:
      </p>
      <ul>
        <li>IP address, user agent, visited path, referrer, and request timing signals</li>
        <li>Risk scores, decision outcomes, and reason codes generated by BotShield&apos;s rules</li>
        <li>Network intelligence such as ASN, hosting-provider classification, VPN or proxy indicators, and related non-customer network metadata</li>
        <li>Recovery reference codes shown on blocked pages when applicable</li>
      </ul>
      <p>
        BotShield uses this information to provide analytics, incident history,
        email alerts, weekly reports, automated challenge or block responses,
        and merchant recovery controls. Storefront security events are retained
        for 30 days and then automatically deleted.
      </p>
      <h2>Simulation And Test Activity</h2>
      <p>
        Diagnostic and simulation activity initiated from the BotShield admin
        app is labeled separately from real storefront traffic. Simulations do
        not alter live enforcement state and are excluded from production
        storefront metrics and reports.
      </p>
      <h2>Fraud Orders (Level 1 Protected Customer Data)</h2>
      <p>
        Fraud Orders is optional. When a merchant connects order access and
        Shopify grants the required protected customer data approval, BotShield
        can request supported Shopify order and order-risk information needed to
        display a review queue inside the app.
      </p>
      <p>Supported fields may include:</p>
      <ul>
        <li>Order identifiers and order name</li>
        <li>Order creation time</li>
        <li>Order total and currency</li>
        <li>Payment and fulfillment status fields exposed by Shopify</li>
        <li>Shopify risk recommendation, risk level, assessment provider title, and supported assessment fact descriptions</li>
      </ul>
      <p>
        BotShield&apos;s v1 Fraud Orders integration does not request customer
        name, customer email, phone, billing address, or shipping address. BotShield
        does not create Shopify&apos;s fraud assessments; it presents supported
        Shopify order-risk information for merchant review.
      </p>
      <p>
        Fraud Orders data is fetched live from Shopify for display and is not
        persisted as Shopify order records inside BotShield&apos;s database.
      </p>
      <h2>Email Delivery Metadata</h2>
      <p>
        When merchants enable alerts or weekly reports, BotShield processes the
        configured alert email address and provider delivery status needed to
        send and confirm merchant notifications. BotShield uses Resend as its
        email delivery provider.
      </p>
      <h2>What BotShield Does Not Intentionally Collect</h2>
      <ul>
        <li>Payment card numbers or account passwords</li>
        <li>Customer name, email, phone, billing address, or shipping address in Fraud Orders v1</li>
        <li>Shopify customer IDs linked to storefront security events</li>
      </ul>
      <h2>Related Documents</h2>
      <p>
        See also the <a href={publicInfo.privacyUrl}>Privacy Policy</a>,{" "}
        <a href={publicInfo.dataRetentionUrl}>Data retention</a>, and{" "}
        <a href={publicInfo.dataDeletionUrl}>Data deletion</a> pages.
      </p>
      <p>
        Questions about data use can be sent to <PublicSupportEmailLink />.
      </p>
    </PublicLegalShell>
  );
}
