import {
  PublicLegalFact,
  PublicLegalRelatedLinks,
  PublicLegalSection,
} from "../components/public/PublicLegalContent";
import { PublicLegalShell, PublicSupportEmailLink } from "../components/public/PublicLegalShell";
import { publicInfo } from "../config/public-info";

const sections = [
  { id: "store-app", label: "Store and app information" },
  { id: "storefront-events", label: "Storefront security events" },
  { id: "simulation", label: "Simulation data" },
  { id: "fraud-orders", label: "Fraud Orders" },
  { id: "notifications", label: "Notifications" },
  { id: "not-collected", label: "What we do not collect" },
];

export const meta = () => [{ title: `Data Use | ${publicInfo.appName}` }];

export default function DataUsePage() {
  return (
    <PublicLegalShell
      title="Data Use"
      summary="How BotShield uses merchant, storefront, and supported Shopify data to provide security, analytics, alerts, and optional Fraud Orders review."
      sections={sections}
    >
      <PublicLegalSection id="store-app" title="Store And App Information">
        <p>BotShield may process:</p>
        <ul>
          <li>Shopify store domain and shop identifiers needed to associate activity with the correct merchant installation</li>
          <li>Shopify app authentication sessions, including staff user identifiers and contact details supplied by Shopify during admin sign-in</li>
          <li>Merchant configuration such as protection settings, alert routing, blocklists, trusted visitor labels and notes, and billing status metadata</li>
        </ul>
      </PublicLegalSection>

      <PublicLegalSection id="storefront-events" title="Storefront Security Events">
        <p>
          When the BotShield theme app embed is enabled, compatible storefront browsers
          may send request context that BotShield uses for security analysis. Depending
          on the event, BotShield may process:
        </p>
        <ul>
          <li>IP address, user agent, visited path, and request timing signals</li>
          <li>Risk scores, decision outcomes, reason codes, and related threat evidence generated by BotShield</li>
          <li>Network intelligence such as ASN, hosting-provider classification, geographic network metadata, and VPN, proxy, datacenter, Tor, or abuse indicators</li>
        </ul>
        <p>
          BotShield uses this information to provide analytics, incident history, email
          alerts, weekly reports, automated challenge or block responses, and merchant
          recovery controls. Blocked storefront pages may display a BotShield reference
          code derived from the related security event identifier.
        </p>
        <PublicLegalFact title="Retention">
          <p>
            Storefront security events are retained for 30 days and then automatically
            deleted while the app remains installed.
          </p>
        </PublicLegalFact>
      </PublicLegalSection>

      <PublicLegalSection id="simulation" title="Simulation Data">
        <p>
          Diagnostic and simulation activity initiated from the BotShield admin app is
          labeled separately from live storefront traffic. Simulation data does not
          alter live enforcement state and is excluded from production storefront
          metrics and reports.
        </p>
      </PublicLegalSection>

      <PublicLegalSection id="fraud-orders" title="Fraud Orders">
        <p>
          Fraud Orders is optional. When a merchant connects order access and Shopify
          grants the required protected customer data approval, BotShield can request
          supported Shopify order and order-risk information needed to display a review
          queue inside the app.
        </p>
        <p>Supported fields include:</p>
        <ul>
          <li>Order identifier and order name</li>
          <li>Order creation time</li>
          <li>Order total and currency</li>
          <li>Payment and fulfillment status fields exposed by Shopify</li>
          <li>Shopify risk recommendation, risk level, assessment provider title, and supported assessment fact descriptions</li>
        </ul>
        <PublicLegalFact title="Level 1 protected customer data">
          <p>
            BotShield does not request customer name, customer email, phone, billing
            address, or shipping address. BotShield does not create Shopify&apos;s
            fraud or risk assessments; it presents supported Shopify order-risk
            information for merchant review.
          </p>
        </PublicLegalFact>
        <p>
          Fraud Orders data is fetched live from Shopify for display and is not
          persisted as Shopify order records inside BotShield&apos;s database.
        </p>
      </PublicLegalSection>

      <PublicLegalSection id="notifications" title="Merchant Notifications">
        <p>
          When merchants enable alerts or weekly reports, BotShield stores and uses the
          merchant-configured alert email address and may retain provider delivery
          status metadata needed to send and confirm notifications. Resend is used as
          BotShield&apos;s email delivery provider.
        </p>
      </PublicLegalSection>

      <PublicLegalSection id="not-collected" title="What BotShield Does Not Intentionally Collect">
        <ul>
          <li>Payment card numbers or account passwords</li>
          <li>Customer name, email, phone, billing address, or shipping address through Fraud Orders</li>
          <li>Shopify customer IDs linked to storefront security events</li>
        </ul>
      </PublicLegalSection>

      <PublicLegalRelatedLinks
        links={[
          { href: publicInfo.privacyUrl, label: "Privacy Policy" },
          { href: publicInfo.dataRetentionUrl, label: "Data retention" },
          { href: publicInfo.dataDeletionUrl, label: "Data deletion" },
          { href: publicInfo.supportUrl, label: "Support" },
        ]}
      />
      <p>
        Questions about data use can be sent to <PublicSupportEmailLink />.
      </p>
    </PublicLegalShell>
  );
}
