import { PublicPage } from "../components/PublicPage";
import { publicInfo } from "../config/public-info";

export const meta = () => [{ title: `Privacy Policy | ${publicInfo.appName}` }];

export default function PrivacyPage() {
  return (
    <PublicPage title="Privacy Policy">
      <p>
        Effective date: {publicInfo.effectiveDate}
      </p>
      <p>
        {publicInfo.appName} helps Shopify merchants monitor suspicious traffic,
        review scan history, and manage storefront protection controls.
      </p>
      <h2>Information We Collect</h2>
      <p>
        We may process Shopify store domain details, app installation records,
        app configuration, scan records, IP addresses, paths, user-agent strings,
        and related threat evidence generated by app scans.
      </p>
      <h2>How We Use Information</h2>
      <p>
        We use information to provide and operate {publicInfo.appName}, detect
        suspicious or abusive traffic behavior, store merchant configuration and
        scan history, improve reliability, and provide support.
      </p>
      <h2>Sharing</h2>
      <p>
        We do not sell merchant data. We may share information with service
        providers when needed to host, secure, support, or operate the app, or
        when required by law.
      </p>
      <h2>Retention And Deletion</h2>
      <p>
        We retain information for as long as needed to operate the app, comply
        with legal obligations, resolve disputes, and enforce agreements. Store
        data is deleted or anonymized when required by Shopify compliance
        webhooks and applicable law.
      </p>
      <h2>Contact</h2>
      <p>
        Privacy questions can be sent to{" "}
        <a href={`mailto:${publicInfo.supportEmail}`}>
          {publicInfo.supportEmail}
        </a>
        .
      </p>
    </PublicPage>
  );
}
